name: CI

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install Python dependencies
        run: pip install '.[test]'
      - name: Rustfmt
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Black
        run: black . --check

  build:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [x86_64, aarch64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          manylinux: auto

  test:
    name: "Test"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Rust tests
        run: cargo test
      - name: Install Python dependencies
        run: pip install '.[test]'
      - name: Run Python tests
        run: pytest
